### ISSUE TITLE
problem avec calibre 1.0.0 et poche 1.3.0 (self hosted)

### ISSUE THREAD

**Issue by alemairebe** [FaustXVI/poche-to-calibre#1]
voici le log d'erreur :
calibre, version 1.0.0 (linux2, isfrozen: False)
Conversion Error: Failed: Fetch news from Poche

Fetch news from Poche
Resolved conversion options
calibre version: 1.0.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': None,
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_download_recipe': False,
 'dont_split_on_page_breaks': True,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': None,
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x27b8290>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0,
 'linearize_tables': False,
 'lrf': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x27b8690>,
 'page_breaks_before': None,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': None,
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': None,
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': '',
 'sr1_search': '',
 'sr2_replace': '',
 'sr2_search': '',
 'sr3_replace': '',
 'sr3_search': '',
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'test': False,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: Recipe Input running
Using custom recipe
Traceback (most recent call last):
  File "/usr/bin/calibre-parallel", line 20, in <module>
    sys.exit(main())
  File "/usr/lib/calibre/calibre/utils/ipc/worker.py", line 189, in main
    result = func(_args, *_kwargs)
  File "/usr/lib/calibre/calibre/gui2/convert/gui_conversion.py", line 25, in gui_convert
    plumber.run()
  File "/usr/lib/calibre/calibre/ebooks/conversion/plumber.py", line 1027, in run
    accelerators, tdir)
  File "/usr/lib/calibre/calibre/customize/conversion.py", line 241, in **call**
    log, accelerators)
  File "/usr/lib/calibre/calibre/ebooks/conversion/plugins/recipe_input.py", line 113, in convert
    ro = recipe(opts, log, self.report_progress)
  File "/usr/lib/calibre/calibre/web/feeds/news.py", line 869, in **init**
    self.browser = self.get_browser()
  File "<string>", line 17, in get_browser
TypeError: unbound method get_browser() must be called with BasicNewsRecipe instance as first argument (got nothing instead)

**Comment by FaustXVI** [comment]
Merci,
Le script a été écris avec un calibre V0.8.51 (dépôts debian). Au vue de l'erreur, l'API de scripts a changé depuis. Je m'installerai la dernière version de calibre sous peu pour corriger le problème.

## 

Thanks,
The script have been wrote with calibre V0.8.51 (debian repository). Looking at the trace, the API may have change for V1.0.0. I'll install the last calibre's version in order to correct the issue.

**Comment by alemairebe** [comment]
For your information, I though you was using the latest version available. so I updated mine to 1.14.0. The problem is still the same. I'll give you some feedback a soon as you update it, or maybe il will propose a patch if i find some time to.

**Comment by alemairebe** [comment]
to solve the problem ; you need to replace 
        br = BasicNewsRecipe.get_browser()
 by 
        br = BasicNewsRecipe.get_browser(self)

**Comment by FaustXVI** [comment]
OK, thanks.
