### ISSUE TITLE
Table des matières

### ISSUE THREAD

**Issue by nicosomb** [FaustXVI/poche-to-calibre#4]
Salut @FaustXVI !

Voici un mail que j'ai reçu : 

```
L'export de Poche vers epub (j'adore !) via Calibre donne une table des matières de ce type : http://pix.toile-libre.org/?img=1388963526.png

D'après le peu que j'ai compris du code python de la recette calibre, c'est au niveau de la variable "key" qui est choisie par la suite comme "titre".

# use reading time as a key
key = self.tag_to_string(div.find(
    'a', attrs={'class': ['reading-time']}))

Amha, ce serait bien si le articles "poché" étaient classés par ordre chronologique inverse (les plus récentes en haut) et surtout si la "clé" utilisée dans la table des matières étaient le titre de la page.
```

**Comment by DmitrySandalov** [comment]
@nicosomb 
Do you want domain as key instead of reading time? Or just article names as a key?

**Comment by nicosomb** [comment]
I don't know what is the best. 
I don't use (yet) poche-to-calibre. 

The "bug" is a mail I received.

**Comment by rboulle** [comment]
Hi, I sent this email :-)

I think it could be nice to have "article names" as a key.
Now, table of contents in epub looks like :
http://pix.toile-libre.org/?img=1388963526.png
The list of all webpages will be better. 
If possible with the last page "poched" at the top 
Thanks.

**Comment by DmitrySandalov** [comment]
Implemented domain as a key. Do we really need each article as a key? 
@rboulle, what do you think?  
![20140108200144](https://f.cloud.github.com/assets/1167276/1869795/f4dda204-787e-11e3-82dc-470bb698432d.png) ![20140108200253](https://f.cloud.github.com/assets/1167276/1869796/f509f2e6-787e-11e3-942c-c4fcdec76602.png)

**Comment by rboulle** [comment]
@DmitrySandalov It is much better :-)

I don't want to be the only one to "decide" but I think that something in RSS style will be great. So it may be even more better to have webpage title as a key. Actually your poche is your very personnal RSS

We can image an extra improvement having as a key the webpage title and just under the very first lines of this pages.

Many thanks :-)
Rémi.

**Comment by FaustXVI** [comment]
Seems good to me. It was on my todo list to found a better table of contents. The idea to group it by domain is very good. Thanks @DmitrySandalov . I think we can improve it by using the title tag of the home page as a key as said @rboulle but the first lines of the pages may be useless and make the table of content hard to read. What do you think ?

**Comment by rboulle** [comment]
@FaustXVI You'r right. Let's keep the table of contents a table of contents. 
Thanks.
